### ISSUE TITLE
Unable to play Mp3 file from azure blob storage

### ISSUE THREAD

**Issue by kwacks** [StefH/Howler.Blazor#1]
Hi, 
Thanks for this great component. I love the simplicity of integrating it. 
I'm getting an error when trying to play an mp3 file from azure storage. Here's the Url: 
https://lookandstore.blob.core.windows.net/863da396-6e44-4b3b-8db1-e447d87b121f/instrumental_mp3_637141046337946343_99lfo/instrumental_mp3?sv=2018-03-28&sr=b&sig=96LJ7bycF3lrtiWbVP5tK6%2BOOIJKfq7eYPO%2FjOT72ns%3D&se=2022-10-04T18%3A23%3A53Z&sp=rl

This fails with the error below. I confirmed the file is downloadable and other online players can access it. My sample also works with the urls in  Any clues on how to fix this? 
Error: 
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $ | LineNumber: 0 | BytePositionInLine: 4. ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
  at System.Text.Json.Utf8JsonReader.TryGetInt32 (System.Int32& value) <0x2136d28 + 0x0001a> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
  at System.Text.Json.Utf8JsonReader.GetInt32 () <0x2136c58 + 0x00008> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
  at System.Text.Json.Serialization.Converters.JsonConverterInt32.Read (System.Text.Json.Utf8JsonReader& reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options) <0x2136ba8 + 0x00004> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
  at System.Text.Json.JsonPropertyInfoNotNullable`4[TClass,TDeclaredProperty,TRuntimeProperty,TConverter].OnRead (System.Text.Json.ReadStack& state, System.Text.Json.Utf8JsonReader& reader) <0x21b23f8 + 0x00032> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
  at System.Text.Json.JsonPropertyInfo.Read (System.Text.Json.JsonTokenType tokenType, System.Text.Json.ReadStack& state, System.Text.Json.Utf8JsonReader& reader) <0x1edbe28 + 0x0007e> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
  at System.Text.Json.JsonSerializer.HandleNull (System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& state) <0x2145490 + 0x00108> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
  at System.Text.Json.JsonSerializer.ReadCore (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& readStack) <0x1ec3e20 + 0x00274> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
   --- End of inner exception stack trace ---
  at System.Text.Json.ThrowHelper.ReThrowWithPath (System.Text.Json.ReadStack& readStack, System.Text.Json.Utf8JsonReader& reader, System.Exception ex) <0x22043b8 + 0x00028> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
  at System.Text.Json.JsonSerializer.ReadCore (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& readStack) <0x1ec3e20 + 0x0032a> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
  at System.Text.Json.JsonSerializer.ReadValueCore (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& readStack) <0x207ccb8 + 0x00546> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
  at System.Text.Json.JsonSerializer.ReadValueCore (System.Text.Json.Utf8JsonReader& reader, System.Type returnType, System.Text.Json.JsonSerializerOptions options) <0x207c210 + 0x0003e> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
  at System.Text.Json.JsonSerializer.Deserialize (System.Text.Json.Utf8JsonReader& reader, System.Type returnType, System.Text.Json.JsonSerializerOptions options) <0x207c130 + 0x00024> in <a8b80a1decbd4fb89df33aca6e6f0fa1>:0 
  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ParseArguments (Microsoft.JSInterop.JSRuntime jsRuntime, System.String methodIdentifier, System.String arguments, System.Type[] parameterTypes) <0x210a648 + 0x0015c> in <3eedf0ca90ca4e72bf6870618ca98c7c>:0 
  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously (Microsoft.JSInterop.JSRuntime jsRuntime, Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo& callInfo, Microsoft.JSInterop.Infrastructure.IDotNetObjectReference objectReference, System.String argsJson) <0x20d2120 + 0x00108> in <3eedf0ca90ca4e72bf6870618ca98c7c>:0 
  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet (Microsoft.JSInterop.JSRuntime jsRuntime, Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo invocationInfo, System.String argsJson) <0x20d1c90 + 0x00092> in <3eedf0ca90ca4e72bf6870618ca98c7c>:0 
    at Object.endInvokeDotNetFromJS (https://localhost:44314/_framework/blazor.webassembly.js:1:9849)
    at Object.invokeJSFromDotNet (https://localhost:44314/_framework/blazor.webassembly.js:1:9475)
    at _mono_wasm_invoke_js_marshalled (https://localhost:44314/_framework/wasm/mono.js:1:165750)
    at wasm-function[6221]:0x11936a
    at wasm-function[1431]:0x402ee
    at wasm-function[636]:0x147cf
    at wasm-function[4996]:0xeb135
    at wasm-function[3247]:0xa0666
    at wasm-function[1324]:0x3af33
    at wasm-function[436]:0xd450

**Comment by StefH** [comment]
I've created a new NuGet which fixes this invoke error.

The error you get when playing this file from blobstorage is:
```
OnLoadError : No codec support for selected audio sources.
```

This means that Howler cannot use the content-type to determine the audio type.

**Comment by kwacks** [comment]
@StefH , thanks for the quick turnaround. 
Now when I try that link, there's no error  and the file doesn't play, though you can see it is a valid mp3 file. 
Does it work for you?

**Comment by kwacks** [comment]
Ah. I see, I just added the OnLoadError handler and I can see the error message.    It is a valid mp3 file, the url has shared access signature tagged on but libraries should still be able to play this. 
I wonder how it's determining the file type?

**Comment by StefH** [comment]
I've create new version (0.9.2) which adds `Formats` to the HowlOptions.

However you also need to fix CORS on your mp3 file on azure blob, else you get error like:
```
Access to XMLHttpRequest at 'https://lookandstore.blob.core.windows.net/863da396-6e44-4b3b-8db1-e447d87b121f/instrumental_mp3_637141046337946343_99lfo/instrumental_mp3?sv=2018-03-28&sr=b&sig=96LJ7bycF3lrtiWbVP5tK6%2BOOIJKfq7eYPO%2FjOT72ns%3D&se=2022-10-04T18%3A23%3A53Z&sp=rl' from origin 'https://localhost:44363' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by kwacks** [comment]
Thanks, fixed CORS and tested and it works quite well.  Thanks for the fast fix!
